Homepage refactor
DigiReal-eu/website pull request #8
Opened 2022-03-25 07:54 UTC by kallepronk

2022-03-25 08:51 UTC, jendafojtik approved these changes

2022-03-25 08:53 UTC, jendafojtik commented on src/components/layout/founders/founders.tsx
> +import BuasLogo from '../../../assets/images/Logo BUas_Black.png';
I think there might be a better way to import all the logos instead of having line per logo since this might become an issue in the future, I'll have a look at that later today and see if I can figure out a feasible solution.

2022-03-27 10:59 UTC, BartvanEijkelenburg requested changes

2022-03-27 10:59 UTC, BartvanEijkelenburg commented on src/components/layout/founders/founders.scss
> +        padding: 0.5em 1em 0.5em 1em;
Mind want to add a transition property here so the button gets a more 'modern' look when hovering.

The cursor does not change, suggesting the button is not clickable, mind want to add cursor: pointer as well.

2022-03-27 10:59 UTC, BartvanEijkelenburg commented on src/components/layout/founders/founders.tsx
> +            <button type="button" className="founders__button">Bekijk partners </button>
Button has no functionality?

Please make it so that it navigates to /partners.

I might be wrong but is the translation missing?

2022-03-27 10:59 UTC, BartvanEijkelenburg commented on src/components/layout/founders/founders.tsx
> +import BuasLogo from '../../../assets/images/Logo BUas_Black.png';
It is possible to create an images.ts file where you 'require' all images, and then you can import that file.

It looks much cleaner and would be nice if you could implement that in the future.

2022-03-28 09:15 UTC, BartvanEijkelenburg commented on src/components/layout/founders/founders.scss
> +        padding: 0.5em 1em 0.5em 1em;
Icon is missing, as discussed in the standup, writing it here so we won't forget.

2022-03-28 09:16 UTC, BartvanEijkelenburg requested changes
As discussed in the startup, a refactor will be needed.

Make sure to fix the lint issues as well before pushing. 

besides that, good job!

2022-04-04 12:17 UTC, BartvanEijkelenburg approved these changes

2022-04-04 12:17 UTC, merged